import {
  Power,
  Volume2,
  Volume1,
  VolumeX,
  Play,
  Pause,
  Square,
  Circle,
  Rewind,
  FastForward,
  SkipForward,
  SkipBack,
  Tv,
  Speaker,
  Snowflake,
  Sun,
  Moon,
  Fan,
  Wind,
  Thermometer,
  Droplet,
  ChevronUp,
  ChevronDown,
  ArrowUpCircle,
  ArrowDownCircle,
  Cable,
  Menu,
  Home,
  ArrowLeft,
  Info,
  ListVideo,
  Settings,
  Mic,
  Lightbulb,
  Zap,
  Hash,
  type LucideIcon,
} from "lucide-react";
import type { IrDevice, IrIcon } from "@/lib/supabase";

export const IR_ICONS: { key: IrIcon; label: string; icon: LucideIcon }[] = [
  { key: "power", label: "Power", icon: Power },
  { key: "volume-up", label: "Vol +", icon: Volume2 },
  { key: "volume-down", label: "Vol −", icon: Volume1 },
  { key: "volume-x", label: "Mute", icon: VolumeX },
  { key: "channel-up", label: "Ch +", icon: ArrowUpCircle },
  { key: "channel-down", label: "Ch −", icon: ArrowDownCircle },
  { key: "chevron-up", label: "Up", icon: ChevronUp },
  { key: "chevron-down", label: "Down", icon: ChevronDown },
  { key: "play", label: "Play", icon: Play },
  { key: "pause", label: "Pause", icon: Pause },
  { key: "stop", label: "Stop", icon: Square },
  { key: "record", label: "Record", icon: Circle },
  { key: "rewind", label: "Rewind", icon: Rewind },
  { key: "fast-forward", label: "Fwd", icon: FastForward },
  { key: "skip-forward", label: "Next", icon: SkipForward },
  { key: "skip-back", label: "Prev", icon: SkipBack },
  { key: "input", label: "Input", icon: Cable },
  { key: "menu", label: "Menu", icon: Menu },
  { key: "home", label: "Home", icon: Home },
  { key: "back", label: "Back", icon: ArrowLeft },
  { key: "info", label: "Info", icon: Info },
  { key: "guide", label: "Guide", icon: ListVideo },
  { key: "settings", label: "Settings", icon: Settings },
  { key: "mic", label: "Mic", icon: Mic },
  { key: "hash", label: "Numbers", icon: Hash },
  { key: "tv", label: "TV", icon: Tv },
  { key: "speaker", label: "Speaker", icon: Speaker },
  { key: "snowflake", label: "Cool", icon: Snowflake },
  { key: "sun", label: "Heat", icon: Sun },
  { key: "moon", label: "Sleep", icon: Moon },
  { key: "fan", label: "Fan", icon: Fan },
  { key: "wind", label: "Wind", icon: Wind },
  { key: "thermometer", label: "Temp", icon: Thermometer },
  { key: "droplet", label: "Dry", icon: Droplet },
  { key: "lightbulb", label: "Light", icon: Lightbulb },
  { key: "zap", label: "Boost", icon: Zap },
];

export function irIconFor(key: string): LucideIcon {
  return IR_ICONS.find((i) => i.key === key)?.icon ?? Power;
}

export const IR_DEVICES: { key: IrDevice; label: string; icon: LucideIcon }[] = [
  { key: "tv", label: "TV", icon: Tv },
  { key: "speaker", label: "Speaker", icon: Speaker },
  { key: "ac", label: "Air Conditioner", icon: Snowflake },
];

export function deviceMeta(key: string) {
  return IR_DEVICES.find((d) => d.key === key) ?? IR_DEVICES[0];
}
