/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ScenesRouteImport } from './routes/scenes'
import { Route as RemotesRouteImport } from './routes/remotes'
import { Route as EventsRouteImport } from './routes/events'
import { Route as DoorRouteImport } from './routes/door'
import { Route as DevicesRouteImport } from './routes/devices'
import { Route as AlarmsRouteImport } from './routes/alarms'
import { Route as IndexRouteImport } from './routes/index'

const ScenesRoute = ScenesRouteImport.update({
  id: '/scenes',
  path: '/scenes',
  getParentRoute: () => rootRouteImport,
} as any)
const RemotesRoute = RemotesRouteImport.update({
  id: '/remotes',
  path: '/remotes',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const DoorRoute = DoorRouteImport.update({
  id: '/door',
  path: '/door',
  getParentRoute: () => rootRouteImport,
} as any)
const DevicesRoute = DevicesRouteImport.update({
  id: '/devices',
  path: '/devices',
  getParentRoute: () => rootRouteImport,
} as any)
const AlarmsRoute = AlarmsRouteImport.update({
  id: '/alarms',
  path: '/alarms',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alarms': typeof AlarmsRoute
  '/devices': typeof DevicesRoute
  '/door': typeof DoorRoute
  '/events': typeof EventsRoute
  '/remotes': typeof RemotesRoute
  '/scenes': typeof ScenesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alarms': typeof AlarmsRoute
  '/devices': typeof DevicesRoute
  '/door': typeof DoorRoute
  '/events': typeof EventsRoute
  '/remotes': typeof RemotesRoute
  '/scenes': typeof ScenesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alarms': typeof AlarmsRoute
  '/devices': typeof DevicesRoute
  '/door': typeof DoorRoute
  '/events': typeof EventsRoute
  '/remotes': typeof RemotesRoute
  '/scenes': typeof ScenesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alarms'
    | '/devices'
    | '/door'
    | '/events'
    | '/remotes'
    | '/scenes'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alarms'
    | '/devices'
    | '/door'
    | '/events'
    | '/remotes'
    | '/scenes'
  id:
    | '__root__'
    | '/'
    | '/alarms'
    | '/devices'
    | '/door'
    | '/events'
    | '/remotes'
    | '/scenes'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlarmsRoute: typeof AlarmsRoute
  DevicesRoute: typeof DevicesRoute
  DoorRoute: typeof DoorRoute
  EventsRoute: typeof EventsRoute
  RemotesRoute: typeof RemotesRoute
  ScenesRoute: typeof ScenesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/scenes': {
      id: '/scenes'
      path: '/scenes'
      fullPath: '/scenes'
      preLoaderRoute: typeof ScenesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/remotes': {
      id: '/remotes'
      path: '/remotes'
      fullPath: '/remotes'
      preLoaderRoute: typeof RemotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/door': {
      id: '/door'
      path: '/door'
      fullPath: '/door'
      preLoaderRoute: typeof DoorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/devices': {
      id: '/devices'
      path: '/devices'
      fullPath: '/devices'
      preLoaderRoute: typeof DevicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alarms': {
      id: '/alarms'
      path: '/alarms'
      fullPath: '/alarms'
      preLoaderRoute: typeof AlarmsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlarmsRoute: AlarmsRoute,
  DevicesRoute: DevicesRoute,
  DoorRoute: DoorRoute,
  EventsRoute: EventsRoute,
  RemotesRoute: RemotesRoute,
  ScenesRoute: ScenesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
